name: path_to_regexp
version: 0.2.1
description: Converts a path such as '/user/:id' into a regular expression.
author: Leon Senft <leonsenft@google.com>
homepage: https://github.com/leonsenft/path_to_regexp

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  # For `package:pedantic/analysis_options.yaml`.
  pedantic: 1.8.0
  test: ^1.3.0
